services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slock
    ports:
      - "5432:5432"
    volumes:
      - ./db.local:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/slock
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
