services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slock
    ports:
      - "5432:5432"
    volumes:
      - ./db.local:/var/lib/postgresql/data
