# https://taskfile.dev
version: '3'
tasks:
  updateSubmodules:
    cmd: git submodule update --remote --merge
  generateOpenApi:
    cmds:
      - task: updateSubmodules
      - cd slock-openapi && npm ci && npm run build
      - ./gradlew :generateOpenApi --stacktrace
  migrateDatabase:
    cmd: ./gradlew :migrateDatabase --stacktrace
  run:
    cmd: ./gradlew :run --console=plain --stacktrace
    interactive: true
