ALTER TABLE users RENAME COLUMN created TO created_at;
ALTER TABLE users RENAME COLUMN updated TO updated_at;
ALTER TABLE sessions RENAME COLUMN created TO created_at;
ALTER TABLE sessions RENAME COLUMN updated TO updated_at;
ALTER TABLE channels RENAME COLUMN created TO created_at;
ALTER TABLE channels RENAME COLUMN updated TO updated_at;
ALTER TABLE participates RENAME COLUMN created TO created_at;
ALTER TABLE participates RENAME COLUMN updated TO updated_at;
ALTER TABLE messages RENAME COLUMN created TO created_at;
ALTER TABLE messages RENAME COLUMN updated TO updated_at;
ALTER TABLE attachments RENAME COLUMN created TO created_at;
ALTER TABLE attachments RENAME COLUMN updated TO updated_at;
ALTER TABLE reactions RENAME COLUMN created TO created_at;
ALTER TABLE reactions RENAME COLUMN updated TO updated_at;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sessions ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sessions ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE channels ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE channels ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE participates ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE participates ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE messages ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE messages ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE attachments ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE attachments ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE reactions ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE reactions ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP USING created_at::timestamp;
ALTER TABLE users ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at::timestamp;
ALTER TABLE sessions ALTER COLUMN created_at TYPE TIMESTAMP USING created_at::timestamp;
ALTER TABLE sessions ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at::timestamp;
ALTER TABLE channels ALTER COLUMN created_at TYPE TIMESTAMP USING created_at::timestamp;
ALTER TABLE channels ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at::timestamp;
ALTER TABLE participates ALTER COLUMN created_at TYPE TIMESTAMP USING created_at::timestamp;
ALTER TABLE participates ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at::timestamp;
ALTER TABLE messages ALTER COLUMN created_at TYPE TIMESTAMP USING created_at::timestamp;
ALTER TABLE messages ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at::timestamp;
ALTER TABLE attachments ALTER COLUMN created_at TYPE TIMESTAMP USING created_at::timestamp;
ALTER TABLE attachments ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at::timestamp;
ALTER TABLE reactions ALTER COLUMN created_at TYPE TIMESTAMP USING created_at::timestamp;
ALTER TABLE reactions ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at::timestamp;